from pyfirmata import Arduino,util
from time import sleep

board = Arduino('COM5')

ledPin1 = board.get_pin("d:13:o")
ledPin1.write(0)
ledPin2 = board.get_pin("d:12:o")
ledPin2.write(0)
ledPin3 = board.get_pin("d:11:o")
ledPin3.write(0)
ledPin4 = board.get_pin("d:10:o")
ledPin4.write(0)
ledPin5 = board.get_pin("d:9:o")
ledPin5.write(0)
ledPin6 = board.get_pin("d:8:o")
ledPin6.write(0)
ledPin7 = board.get_pin("d:7:o")
ledPin7.write(0)
ledPin8 = board.get_pin("d:6:o")
ledPin8.write(0)


while True:
    ledPin1.write(1)
    sleep(0.3)
    ledPin1.write(0)
    sleep(0.2)
    ledPin2.write(1)
    sleep(0.3)
    ledPin2.write(0)
    sleep(0.2)
    ledPin3.write(1)
    sleep(0.3)
    ledPin3.write(0)
    sleep(0.2)
    ledPin4.write(1)
    sleep(0.3)
    ledPin4.write(0)
    sleep(0.2)
    ledPin5.write(1)
    sleep(0.3)
    ledPin5.write(0)
    sleep(0.2)
    ledPin6.write(1)
    sleep(0.3)
    ledPin6.write(0)
    sleep(0.2)
    ledPin7.write(1)
    sleep(0.3)
    ledPin7.write(0)
    sleep(0.2)
    ledPin8.write(1)
    sleep(0.3)
    ledPin8.write(0)
    sleep(0.2)
    board.exit()